import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const projetos = [
    {nome: "Helo Realtor", url: "https://site-imobiliario-frontend.vercel.app/"},
    {nome: "Jordan Shoes", url: "https://desafios-front-end-jordan-shoes.vercel.app/"},
    {nome: "Mini Blog", url: "https://desafios-front-end-blog.vercel.app/"}
  ]
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main styles={styles.main}>
      {projetos.map((projeto, index) => (
          <div key={index}>
            <h2>{projeto.nome}</h2>
            <img src="/assets/iphone.png" alt="oi"></img>
            <iframe src={projeto.url} width="500px" height="500px" allowFullScreen></iframe>

            <a href={projeto.url}>{projeto.nome}</a>
          </div>
        ))}
      </main>
    </>
  );
}
