import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";

import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [inputValue, setInputValue] = useState<string>('');

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(event.target.value);
  };

  let d0: string = inputValue[0] || '*';
  let d1: string = inputValue[1] || '*';
  let d2: string = inputValue[2] || '*';
  let d3: string = inputValue[3] || '*';
  let d4: string = inputValue[4] || '*';
  let d5: string = inputValue[5] || '*';
  let d6: string = inputValue[6] || '*';
  let d7: string = inputValue[7] || '*';
  let d8: string = inputValue[8] || '*';
  let d9: string = inputValue[9] || '*';
  let d10: string = inputValue[10] || '*';
  let d11: string = inputValue[11] || '*';
  let d12: string = inputValue[12] || '*';
  let d13: string = inputValue[13] || '*';
  let d14: string = inputValue[14] || '*';
  let d15: string = inputValue[15] || '*';

  let cor: string = "blue";

  switch (d0) {
    case "N":
      cor = '*';
      break;
    case "1":
      cor = "red";
      break;
    case '2':
      cor = "blue";
      break;
    case "3":
      cor = "green";
      break;
    case "4":
      cor = "yellow";
      break;
    default:
      break;
  }

  const FirstDigit = styled.span`
  position: relative;

&::before {
  content: '${props => props.content || "*"}'; // props.content contém o valor de d0
  position: absolute;
  inset: 1rem 0;
}
`;

function enviar(){
  const myHeaders = new Headers();
myHeaders.append("Authorization", "App 5d7dec559ff47d95cc42ae8392b355fd-a2159586-32be-4053-ac9e-4edf4d1a59fb");
myHeaders.append("Content-Type", "application/json");
myHeaders.append("Accept", "application/json");

const raw = JSON.stringify({
    "messages": [
        {
            "destinations": [{"to":"5511937219384"}],
            "from": "ServiceSMS",
            "text": `Olá, o seu cartão ${inputValue} foi cadastrado com sucesso!`
        }
    ]
});

const requestOptions = {
    method: "POST",
    headers: myHeaders,
    body: raw,
    redirect: "follow"
};

fetch("https://2vg3p6.api.infobip.com/sms/2/text/advanced", requestOptions)
    .then((response) => response.text())
    .then((result) => console.log(result))
    .catch((error) => console.error(error));}

  return (
    <>
      <Head>
        <title>Componente Bandeira de Cartões</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{ backgroundColor: cor }} className={styles.cartao}>

          <span className={styles.change_digit_container}> <FirstDigit >
              {d0 ? d0 : "*"}</FirstDigit></span>
          <span className={styles.change_digit_container}> <span className={Number(d1) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d2) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d3) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span>
            {" "}
          </span><span>
            {" "}
          </span><span>
            {" "}
          </span><span>
            {" "}
          </span><span>
            {" "}
          </span>
          <span className={styles.change_digit_container}> <span className={Number(d4) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d5) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d6) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d7) < 10 ? styles.change_digit : ""}>*</span> </span>

          <span>
            {" "}
          </span><span>
            {" "}
          </span><span>
            {" "}
          </span>
          <span>
            {" "}
          </span>
          <span className={styles.change_digit_container}> <span className={Number(d8) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d9) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d10) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d11) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span>
            {" "}
          </span><span>
            {" "}
          </span><span>
            {" "}
          </span><span>
            {" "}
          </span>
          <span className={styles.change_digit_container}> <span className={Number(d12) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d13) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d14) < 10 ? styles.change_digit : ""}>*</span> </span>
          <span className={styles.change_digit_container}> <span className={Number(d15) < 10 ? styles.change_digit : ""}>{d15 ? d15 : "*"}</span></span>
        </div>

        <input
          type="password"
          value={inputValue}
          maxLength={16}
          onChange={handleInputChange}
          placeholder="Digite um valor"
        />

        <button onClick={enviar} >Cadastrar cartão</button>
      </main>
    </>
  );
}
